
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password: anshu
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  user.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
user.oauth.clientId: devglan-client
user.oauth.clientSecret: devglan-secret
user.oauth.redirectUris: http://localhost:8081/login
user.oauth.user.username: Alex123
user.oauth.user.password: password

user.oauth.accessTokenValidity: 3600
user.oauth.refreshTokenValidity: 21600
security.oauth2.resource.filter-order: 3